description: Courier's settings
required: true
content:
  application/json:
    schema:
      type: object
      properties:
        distance_limit: 
          type: number
          description: Maximum distance the courier is willing to travel for an order.
        vehicle_type:
          type: string
          description: Specifies the type of vehicle the courier uses.
          enum:
            - bicycle
            - motorcycle
            - car
            - van
        min_payout:
          type: number
          description: The minimum amount the courier wants to be paid for a delivery.
