summary: Retrieve the quick-access settings that are frequently modified for the current courier
operationId: getCourierQuickAccessSettings
responses:
  '200':
    description: Successfully retrieved the side panel information
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/CourierQuickAccessSettings'
  '400':
    description: Bad request (e.g., invalid request parameters)
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
  '404':
    description: Courier not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
  '500':
    description: Unexpected server error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
