summary: Retrieve courier's general settings
operationId: getCourierFullSettings
responses:
  '200':
    description: Successfully retrieved the general settings
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/CourierFullSettings'
  '400':
    description: Bad request (e.g., invalid request format)
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
  '404':
    description: Courier not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
  '500':
    description: Unexpected server error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
