# pagination
PaginationPageQueryParam:
  name: page
  in: query
  description: The page number for pagination (optional)
  required: false
  schema:
    type: integer
    default: 10
    format: int32
      
PaginationPageOffsetQueryParam:
  name: perPage
  in: query
  schema:
    type: integer
    minimum: 1
    maximum: 100
  description: The number of items per page (optional)
