openapi: '3.0.0'
info:
  title: 'Courier API Protocol'
  description: A dedicated set of communication endpoints designed to facilitate interactions between delivery couriers and the associated order management system
  version: '0.0.0'
  contact: 
    email: kselberg@princeton.edu
security:
  - OAuth2: [courier]

paths:
  /auth/signup:
    post:
      $ref: './paths/auth/Signup.yaml'
  /auth/login:
    post:
      $ref: './paths/auth/Login.yaml'
  /auth/{provider}/redirect:
    get: 
      $ref: './paths/auth/AuthRedirect.yaml'
  /auth/{provider}/callback:
    get:
      $ref: './paths/auth/AuthCallback.yaml'
  /auth/logout:
    post:
      $ref: './paths/auth/Logout.yaml'
  /auth/request-password-reset:
    get:
      $ref: './paths/auth/PasswordResetRequest.yaml'
  /auth/password-reset:
    post:
      $ref: './paths/auth/PasswordReset.yaml'
  /couriers/me:
    get:
      $ref: './paths/couriers/GetCourier.yaml'
  /couriers/general:
    get:
      $ref: './paths/couriers/GetCourierGeneralSettings.yaml'
    patch:
      $ref: './paths/couriers/UpdateCourierGeneralSettings.yaml'
  /couriers/availability:
    patch:
      $ref: './paths/couriers/UpdateCourierAvailability.yaml'
  /couriers/order-setting:
    patch:
      $ref: './paths/couriers/UpdateCourierOrderSetting.yaml'
  /couriers/node:
    patch:
      $ref: './paths/couriers/UpdateCourierNode.yaml'
  /couriers/side-panel:
    get:
      $ref: './paths/couriers/GetCourierSidePanel.yaml'
    patch:
      $ref: './paths/couriers/UpdateCourierSidePanel.yaml'
  /nodes:
    get:
      $ref: './paths/nodes/GetNodes.yaml'
  /offers:
    get:
      $ref: './paths/offers/GetOffers.yaml'
  /offers/{offer_id}:
    get:
      $ref: './paths/offers/GetOffer.yaml'
    patch:
      $ref: './paths/offers/UpdateOffer.yaml'
  /deliveries:
    get:
      $ref: './paths/deliveries/GetDeliveries.yaml'
  /deliveries/{delivery_id}:
    get:
      $ref: './paths/deliveries/GetDelivery.yaml'
  /deliveries/{delivery_id}/items:
    get:
      $ref: './paths/deliveries/GetDeliveryItems.yaml'
  /deliveries/{delivery_id}/status:
    patch:
      $ref: './paths/deliveries/UpdateDeliveryStatus.yaml'
  /deliveries/{delivery_id}/merchant-comments/{comment_id}/upvote:
    patch:
      $ref: './paths/deliveries/UpvoteDeliveryMerchantComment.yaml'
  /deliveries/{delivery_id}/contact-customer:
    post:
      $ref: './paths/deliveries/ContactCustomer.yaml'
  /earnings:
    get:
      $ref: './paths/earnings/GetEarnings.yaml'
  /payouts:
    post:
      $ref: './paths/payouts/RequestPayout.yaml'
  /payouts/stripe/connect/initiate:
    get:
      $ref: './paths/payouts/stripe/ConnectInitiate.yaml'
  /payouts/stripe/connect/callback:
    get:
      $ref: './paths/payouts/stripe/ConnectCallback.yaml'
components:
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
  schemas:
    $ref: './components/schemas.yaml'
  parameters: 
    $ref: './components/parameters.yaml'
  requestBodies: 
    $ref: './components/requestBodies.yaml'
  headers:
    $ref: './components/headers.yaml'