openapi: '3.0.0'
info:
  title: 'Courier API Protocol'
  description: A dedicated set of communication endpoints designed to facilitate interactions between delivery couriers and the associated order management system
  version: '0.0.0'
  contact: 
    email: kselberg@princeton.edu
security:
  - NodeAuth: [] # API key passed in the header for specific node?
  - OAuth2: [courier]

paths:
  /couriers:
    get:
      $ref: './paths/couriers/GetCouriers.yaml'
    post:
      $ref: './paths/couriers/CreateCourier.yaml'
  /couriers/{courier_id}:
    get:
      $ref: './paths/couriers/GetCourier.yaml'
  /couriers/login:
    post:
      $ref: './paths/couriers/Login.yaml'
  /couriers/logout:
    post:
      $ref: './paths/couriers/Logout.yaml'
  /couriers/password-reset/request:
    post:
      $ref: './paths/couriers/PasswordResetRequest.yaml'
  /couriers/password-reset:
    post:
      $ref: './paths/couriers/PasswordReset.yaml'
  /couriers/auth/{provider}/initiate:
    get: 
      $ref: './paths/couriers/AuthInitiate.yaml'
  /couriers/auth/{provider}/callback:
    get:
      $ref: './paths/couriers/AuthCallback.yaml'
  /couriers/update-settings:
    patch:
      $ref: './paths/couriers/UpdateCourierSettings.yaml'
  /couriers/migrate-account:
    patch:
      $ref: './paths/couriers/MigrateCourierAccount.yaml'
  /couriers/earnings:
    get:
      $ref: './paths/couriers/GetEarnings.yaml'
  /couriers/earnings/receive:
    post:
      $ref: './paths/couriers/ReceiveEarnings.yaml'
  /couriers/deliveries:
    get:
      $ref: './paths/couriers/GetDeliveries.yaml'
  /couriers/deliveries/{delivery_id}:
    get:
      $ref: './paths/couriers/GetDelivery.yaml'
  /payments/stripe/connect/initiate:
    get:
      $ref: './paths/payments/stripe/ConnectInitiate.yaml'
  /payments/stripe/connect/callback:
    get:
      $ref: './paths/payments/stripe/ConnectCallback.yaml'
  /orders:
    get:
      $ref: './paths/orders/GetOrders.yaml'
  /orders/{order_id}:
    get:
      $ref: './paths/orders/GetOrderInfo.yaml'
  /orders/{order_id}/update-status:
    patch:
      $ref: './paths/orders/UpdateOrderStatus.yaml'
  /orders/{order_id}/navigate:
    get:
      $ref: './paths/orders/GetNavigationLink.yaml'
  /orders/{order_id}/contact:
    post:
      $ref: './paths/orders/Contact.yaml'
  /orders/{order_id}/confirm-delivery:
    patch:
      $ref: './paths/orders/ConfirmDelivery.yaml'
components:
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
  schemas:
    $ref: './components/schemas.yaml'
  parameters: 
    $ref: './components/parameters.yaml'
  requestBodies: 
    $ref: './components/requestBodies.yaml'
  headers:
    $ref: './components/headers.yaml'